Repository corona-warn-app/cwa-verification-server, pull requests merged in 2020-07, with the labels that each got.

#177 feat: improvement-logs-cdc
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
Labels: enhancement

#178 fix: improve logs for cdc and increase spring version
  pom.xml
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
Labels: code improvement

#180 Feat/doc update
  docs/architecture-overview.md
Labels: documentation

#181 Fix: Readme.md
  README.md
Labels: bug

#187 doc: rate limit, teleTAN crypto spec
  docs/architecture-overview.md
Labels: documentation

#172 feat: added rate limiting for TeleTan creation
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
  src/main/java/app/coronawarn/verification/controller/InternalTanController.java
  src/main/java/app/coronawarn/verification/domain/VerificationTan.java
  src/main/java/app/coronawarn/verification/repository/VerificationTanRepository.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/main/resources/application.yml
  src/test/java/app/coronawarn/verification/TestUtils.java
  src/test/java/app/coronawarn/verification/VerificationApplicationInternalTest.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: enhancement

#91 add a simple filter which prevents BSI issue #55
  src/main/java/app/coronawarn/verification/config/RequestSizeLimitFilter.java
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
  src/main/resources/application.yml
  src/test/java/app/coronawarn/verification/VerificationApplicationExternalTest.java
  src/test/java/app/coronawarn/verification/VerificationApplicationExternalTestHttp.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
Labels: bug, implemented
