Repository corona-warn-app/cwa-verification-server, pull requests merged in 2020-06, with the labels that each got.

#111 Fix test and docu improvements
  pom.xml
  src/main/java/app/coronawarn/verification/client/LabServerClient.java
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/controller/VerificationExceptionHandler.java
  src/main/java/app/coronawarn/verification/model/AppSessionSourceOfTrust.java
  src/main/java/app/coronawarn/verification/model/HashedGuid.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenKeyType.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenRequest.java
  src/main/java/app/coronawarn/verification/model/TanSourceOfTrust.java
  src/main/java/app/coronawarn/verification/model/TanType.java
  src/main/java/app/coronawarn/verification/model/TeleTan.java
  src/main/java/app/coronawarn/verification/model/TestResult.java
  src/main/java/app/coronawarn/verification/service/EntitiesCleanupService.java
  src/main/java/app/coronawarn/verification/service/LabServerService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
  src/test/java/app/coronawarn/verification/service/LabServerServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: documentation, enhancement

#123 feat: spring security integration and logging
  pom.xml
  src/main/java/app/coronawarn/verification/VerificationApplication.java
  src/main/java/app/coronawarn/verification/config/SecurityConfig.java
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/main/resources/application.yml
Labels: enhancement

#122 feat: integration of result server status redeemed and docu improvements
  src/main/java/app/coronawarn/verification/client/LabServerClient.java
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/exception/VerificationServerException.java
  src/main/java/app/coronawarn/verification/model/HashedGuid.java
  src/main/java/app/coronawarn/verification/model/LabTestResult.java
  src/main/java/app/coronawarn/verification/model/RegistrationToken.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenRequest.java
  src/main/java/app/coronawarn/verification/model/Tan.java
  src/main/java/app/coronawarn/verification/model/TeleTan.java
  src/main/java/app/coronawarn/verification/model/TestResult.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/service/LabServerServiceTest.java
Labels: enhancement

#127 fix: Teletan will be verified if it is expired
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: bug

#131 Creating default values for all configuration class values to prevent null pointer exception when a property is not set
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
Labels: in progress

#138 Update architecture-overview.md and default configuration
  docs/architecture-overview.md
  src/main/resources/application.yml
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
Labels: enhancement

#42 Fix User Story References
  docs/architecture-overview.md
Labels: documentation, in progress

#145 fix: find the expected entity
  src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
Labels: bug

#142 feat: ratelimiting-teletan-format
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: enhancement

#147 feat: set JWT enabled configurable
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
  src/main/java/app/coronawarn/verification/service/JwtService.java
  src/main/resources/application.yml
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
Labels: code improvement

#151 feat: simplify ssl
  pom.xml
  src/main/java/app/coronawarn/verification/client/TestResultServerClientConfig.java
  src/main/java/app/coronawarn/verification/client/TestResultServerClientProvider.java
  src/main/java/app/coronawarn/verification/client/TestResultServerClientProviderNoSsl.java
  src/main/java/app/coronawarn/verification/client/TestResultServerClientProviderSsl.java
  src/main/resources/application.yml
Labels: in progress

#159 Corrected teleTAN specification in architecture-overview.md
  docs/architecture-overview.md
Labels: documentation

#170 Fix typo in API description
  api-docs.json
Labels: in review

#103 use license-maven-plugin to allow generation of license file headers
  CONTRIBUTING.md
  pom.xml
  templates/file-header.txt
Labels: in progress

#160 Minor code quality improvements
  src/main/java/app/coronawarn/verification/client/TestResultServerClientConfig.java
  src/main/java/app/coronawarn/verification/domain/VerificationTan.java
  src/main/java/app/coronawarn/verification/model/AuthorizationRole.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: in review

#167 Speed up unit tests
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
  src/test/java/app/coronawarn/verification/service/TestResultServerServiceTest.java
Labels: in review

#169 fix: Custom validator for Registration Token Request
  pom.xml
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenRequest.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/validator/RegistrationTokenKeyConstraint.java
  src/main/java/app/coronawarn/verification/validator/RegistrationTokenRequestValidator.java
Labels: code improvement, enhancement, in progress

#161 Replace wrong copyright holder in header
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
Labels: in progress

#163 fix: correct registration key validation
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
Labels: in review

#155 Feat/improvement logs regarding cdc
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
Labels: code improvement

#116 update figures to match solution architecture
  docs/architecture-overview.md
  docs/architecture_overview.svg
  docs/sw_design_verification.svg
Labels: documentation

#41 Reference Create Registration Token for E06.01
  docs/architecture-overview.md
Labels: documentation, in progress

#165 Fix Issue #107 Unnecessary complexity
  docs/architecture-overview.md
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/domain/VerificationTan.java
  src/main/java/app/coronawarn/verification/model/AuthorizationRole.java
  src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
  src/test/java/app/coronawarn/verification/service/TestResultServerServiceTest.java
Labels: code improvement

#157 fix: integration-JWT
  pom.xml
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/model/AuthorizationToken.java
  src/main/java/app/coronawarn/verification/service/JwtService.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
Labels: bug, dependencies

#171 Fix: Update the release to 1.0.1 in POM-File
  pom.xml
Labels: enhancement

#175 feature/automatic release notes generation
  .grenrc.js
  CHANGELOG.md
Labels: enhancement
