Repository corona-warn-app/cwa-verification-server, pull requests merged in 2020-05, with the labels that each got.

#50 fix GUID_HASH_PATTERN
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
Labels: security

#57 feat: ci refactor
  .github/workflows/ci-dockerlint.yml
  .github/workflows/ci.yml
  Dockerfile
  DockerfileCi
  Jenkinsfile
  pom.xml
Labels: enhancement

#66 feat: ci pr improvements
  .github/workflows/ci-dockerfile.yml
  .github/workflows/ci.yml
Labels: enhancement

#70 feat: ci sonar disabled for pr
  .github/workflows/ci.yml
Labels: enhancement

#65 Fix TAN_TAN_PATTERN to include regex meta characters
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: enhancement

#75 fix: spring repackage
  DockerfilePaaS
  pom.xml
Labels: bug

#76 Fix/Add JUnit-Tests to increase the codecoverage
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: enhancement

#72 fix: ci remove set env
  .github/workflows/ci.yml
Labels: enhancement

#81 fix: gitattributes
  .gitattributes
  src/main/java/app/coronawarn/verification/client/LabServerClient.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenRequest.java
  src/main/java/app/coronawarn/verification/service/LabServerService.java
Labels: code improvement

#82 feat: spring improvements
  src/main/java/app/coronawarn/verification/VerificationApplication.java
  src/main/java/app/coronawarn/verification/client/HashedGuid.java
  src/main/java/app/coronawarn/verification/client/LabServerClient.java
  src/main/java/app/coronawarn/verification/client/TestResult.java
  src/main/java/app/coronawarn/verification/config/OpenApiConfig.java
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/domain/VerificationTan.java
  src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
  src/main/java/app/coronawarn/verification/repository/VerificationTanRepository.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/main/java/app/coronawarn/verification/service/LabServerService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/LabServerServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: enhancement

#73 fix: documentation
  docs/architecture-overview.md
  src/main/java/app/coronawarn/verification/service/TanService.java
Labels: documentation

#48 fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#56 Update architecture-overview.md
  docs/architecture-overview.md
Labels: community, documentation

#63 improve README.md
  README.md
Labels: documentation

#97 fix: the usage of JPA findOne
  src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
Labels: bug

#96 fix: add Teletan to TestResult
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
Labels: bug, enhancement

#101 feat: implementation of the cleanup concept
  src/main/java/app/coronawarn/verification/VerificationApplication.java
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
  src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
  src/main/java/app/coronawarn/verification/repository/VerificationTanRepository.java
  src/main/java/app/coronawarn/verification/service/EntitiesCleanupService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/main/resources/application.yml
  src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java
Labels: enhancement

#102 fix: Validation on Input Parameter (Issue #33)
  pom.xml
  src/main/java/app/coronawarn/verification/controller/VerificationController.java
  src/main/java/app/coronawarn/verification/controller/VerificationExceptionHandler.java
  src/main/java/app/coronawarn/verification/exception/VerificationServerException.java
  src/main/java/app/coronawarn/verification/model/RegistrationToken.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenRequest.java
  src/main/java/app/coronawarn/verification/model/Tan.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/VerificationApplicationTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: bug, enhancement

#87 use primitive int instead of wrapper type Integer
  src/main/java/app/coronawarn/verification/domain/VerificationAppSession.java
  src/main/java/app/coronawarn/verification/model/LabTestResult.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
Labels: in review
