Repository corona-warn-app/cwa-verification-server, pull requests merged in 2021-01, with the labels that each got.

#216 fix: naming in ExternalTanController
  src/main/java/app/coronawarn/verification/controller/ExternalTanController.java
Labels: in review

#212 rename variable to reflect it's type
  src/main/java/app/coronawarn/verification/controller/ExternalTestStateController.java
Labels: enhancement, in review

#94 Migrate from JUnit 4 to JUnit 5
  pom.xml
  src/test/java/app/coronawarn/verification/VerificationApplicationExternalTest.java
  src/test/java/app/coronawarn/verification/VerificationApplicationInternalTest.java
  src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
  src/test/java/app/coronawarn/verification/service/TestResultServerServiceTest.java
Labels: enhancement, in review

#128 Improve generations of tele-tans
  src/main/java/app/coronawarn/verification/service/TanService.java
Labels: code improvement, in review

#164 fix: handle unsupported content type and HTTP method
  src/main/java/app/coronawarn/verification/controller/VerificationExceptionHandler.java
Labels: enhancement, in review

#110 make sure TeleTANs are unique in the database
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
Labels: enhancement, in review
