Repository corona-warn-app/cwa-verification-server, pull requests merged in 2022-01, with the labels that each got.

#257 Bump copyright year in README.md
  README.md
Labels: documentation

#259 Chore: Update Dependencies, Update File Header
  pom.xml
  src/main/java/app/coronawarn/verification/VerificationApplication.java
  src/main/java/app/coronawarn/verification/client/IamClient.java
  src/main/java/app/coronawarn/verification/client/TestResultServerClient.java
  src/main/java/app/coronawarn/verification/client/TestResultServerClientConfig.java
  src/main/java/app/coronawarn/verification/config/LocalSecurityConfig.java
  src/main/java/app/coronawarn/verification/config/MtlsSecurityConfig.java
  src/main/java/app/coronawarn/verification/config/OpenApiConfig.java
  src/main/java/app/coronawarn/verification/config/RequestSizeLimitFilter.java
  src/main/java/app/coronawarn/verification/config/VerificationApplicationConfig.java
  src/main/java/app/coronawarn/verification/controller/ExternalTanController.java
  src/main/java/app/coronawarn/verification/controller/ExternalTestStateController.java
  src/main/java/app/coronawarn/verification/controller/ExternalTokenController.java
  src/main/java/app/coronawarn/verification/controller/InternalTanController.java
  src/main/java/app/coronawarn/verification/controller/InternalTestStateController.java
  src/main/java/app/coronawarn/verification/controller/VerificationExceptionHandler.java
  src/main/java/app/coronawarn/verification/domain/VerificationAppSession.java
  src/main/java/app/coronawarn/verification/domain/VerificationTan.java
  src/main/java/app/coronawarn/verification/exception/VerificationServerException.java
  src/main/java/app/coronawarn/verification/model/AppSessionSourceOfTrust.java
  src/main/java/app/coronawarn/verification/model/AuthorizationRole.java
  src/main/java/app/coronawarn/verification/model/AuthorizationToken.java
  src/main/java/app/coronawarn/verification/model/Certs.java
  src/main/java/app/coronawarn/verification/model/HashedGuid.java
  src/main/java/app/coronawarn/verification/model/InternalTestResult.java
  src/main/java/app/coronawarn/verification/model/Key.java
  src/main/java/app/coronawarn/verification/model/LabTestResult.java
  src/main/java/app/coronawarn/verification/model/RegistrationToken.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenKeyType.java
  src/main/java/app/coronawarn/verification/model/RegistrationTokenRequest.java
  src/main/java/app/coronawarn/verification/model/Tan.java
  src/main/java/app/coronawarn/verification/model/TanSourceOfTrust.java
  src/main/java/app/coronawarn/verification/model/TanType.java
  src/main/java/app/coronawarn/verification/model/TeleTan.java
  src/main/java/app/coronawarn/verification/model/TeleTanType.java
  src/main/java/app/coronawarn/verification/model/TestResult.java
  src/main/java/app/coronawarn/verification/repository/VerificationAppSessionRepository.java
  src/main/java/app/coronawarn/verification/repository/VerificationTanRepository.java
  src/main/java/app/coronawarn/verification/service/AppSessionService.java
  src/main/java/app/coronawarn/verification/service/EntitiesCleanupService.java
  src/main/java/app/coronawarn/verification/service/FakeDelayService.java
  src/main/java/app/coronawarn/verification/service/FakeRequestService.java
  src/main/java/app/coronawarn/verification/service/HashingService.java
  src/main/java/app/coronawarn/verification/service/JwtService.java
  src/main/java/app/coronawarn/verification/service/TanService.java
  src/main/java/app/coronawarn/verification/service/TestResultServerService.java
  src/main/java/app/coronawarn/verification/validator/RegistrationTokenKeyConstraint.java
  src/main/java/app/coronawarn/verification/validator/RegistrationTokenRequestValidator.java
  src/test/java/app/coronawarn/verification/TestUtils.java
  src/test/java/app/coronawarn/verification/VerificationApplicationExternalTest.java
  src/test/java/app/coronawarn/verification/VerificationApplicationExternalTestHttp.java
  src/test/java/app/coronawarn/verification/VerificationApplicationExternalTestWorkaround.java
  src/test/java/app/coronawarn/verification/VerificationApplicationInternalTest.java
  src/test/java/app/coronawarn/verification/service/EntitiesCleanupServiceTest.java
  src/test/java/app/coronawarn/verification/service/HashingServiceTest.java
  src/test/java/app/coronawarn/verification/service/JwtServiceTest.java
  src/test/java/app/coronawarn/verification/service/TanServiceTest.java
  src/test/java/app/coronawarn/verification/service/TestResultServerServiceTest.java
Labels: chore

#258 Fix: Seperate Unique Constraints for hashed_guid and hashed_guid_dob
  src/main/resources/db/changelog.yml
  src/main/resources/db/changelog/v007-add-seperate-unique-constraints-for-hashed-guid.yml
Labels: bug
